spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myshop?useUnicode=true&serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf8
    username: root
    password: root

logging:
  level:
    root: info
    com.orm.demo: debug

mybatis-plus:
  configuration:
    cache-enabled: true